export const CATEGORIES_ACTION_TYPES = {
  //SET_CATEGORIES_MAP: "SET_CATEGORIES_MAP",
  //SET_CATEGORIES: "SET_CATEGORIES", //158

  ////170. Redux-Thunk for async redux
  FETCH_CATEGORIES_START: "FETCH_CATEGORIES_START",
  FETCH_CATEGORIES_SUCCESS: "FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_FAILED: "FETCH_CATEGORIES_FAILED",
};
